version: '3.8'
services:
  traintickets:
    image: pavankumarsangisetti/traintickets:latest
    ports:
       - "81:80"
    deploy:
       replicas: 3

  mobilerecharge:
     image: pavankumarsangisetti/mobilerecharge:latest
     ports:
         - "82:80"
     deploy:
         replicas: 3
  movietickets:
     image: pavankumarsangisetti/movietickets:latest
     ports:
         - "83:80"
     deploy:
         replicas: 3

  electricitybill:
     image: pavankumarsangisetti/electricitybills:latest
     ports:
         - "84:80"
     deploy:
         replicas: 3

